version: '3'
services:
  bot:
    image: "rust"
    volumes:
      - .:/bot
    working_dir: /bot
    command: cargo r -r
    environment:
      SURR_URL: "db:8000"
  db:
    build: surrealdb/surrealdb:latest
    command: "start --user ${SURR_USER} --pass ${SURR_PASS} --bind 0.0.0.0:8000 file://data/srdb.db"
    ports: 
      - "8000:8000"
